swagger: '2.0'
schemes:
  - http
basePath: /
info:
  version: 1.0.0
  title: ChatBot API
  description: Projekt zaliczeniowy na zajęcia z Projektu Programistycznego, Uniwersytet Ekonomiczny w Katowicach, informatyka, niestacjonarne, 2 grupa, rok 2021/2022
tags:
  - name: main
    description: komendy ogólne związane z API
  - name: spambot
    description: komendy związane z obsługą ChatBota rozpoznającego tekst będący spamem
  - name: questionbot
    description: komendy związane z obsługą ChatBota odpowiadającego na pytania
paths:
  /:
    get:
      summary: informacje o API i jego autorach
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            example: {
              'przedmiot': 'Projekt programistyczny',
              'kierunek': 'Informatyka',
              'grupa': 'Studia niestacjonarne',
              'rok': '2021/2022',
              'uczelnia': 'Uniwersytet Ekonomiczny',
              'autorzy': [
                'Artur Leśnik',
                'Alicja Pęgiel'
              ]
            }
      tags:
        - main
  /learn/spam:
    post:
      summary: uczy bota spamowego nowych danych przy pomocy danych nauki
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Nowe dane nauki do rozpoznawania spamu"
          required: true
          schema:
            $ref: "#/definitions/SpamLearnData"
      responses:
        '200':
          description: OK
          schema:
            example: {
              'operation': 'success'
            }
        '400':
          description: Brak wymaganego parametru
          schema:
            example: {
              "message": {
                "textData": "Missing required parameter in the JSON body or the post body or the query string"
              }
            }
        '422':
          description: Parametr niewłaściwy
          schema:
            example: { 'textData' : 'empty' }
      tags:
        - spambot
  /learn/question:
    post:
      summary: "uczy bota odpowiedzi na nowy zestaw pytanie i odpowiedź"
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: "body"
          name: "body"
          description: "Nowe dane nauki do pytań i odpowiedzi"
          required: true
          schema:
            $ref: "#/definitions/QuestionLearnData"
      responses:
        '200':
          description: OK
          schema:
            example: {
              'operation': 'success'
            }
        '400':
          description: Brak wymaganego parametru
          schema:
            example: {
              "message": {
                "question": "Missing required parameter in the JSON body or the post body or the query string"
              }
            }
        '422':
          description: Parametr niewłaściwy
          schema:
            example: { 'question': 'too short, minimum 5 chars' }
      tags:
        - questionbot
definitions:
  SpamLearnData:
    type: "object"
    properties:
      textData:
        type: "string"
        description: "Dane tekstowe, które posłużą jako dane nauki w aplikacji."
      isSpam:
        type: "string"
        description: "Oznaczenie, czy w czasie nauki traktować powyższe dane jako spam czy prawidłowy tekst."
        enum:
          - "spam"
          - "not-spam"
    xml:
      name: "SpamLearnData"
  QuestionLearnData:
    type: "object"
    properties:
      question:
        type: "string"
        description: "Pytanie do nauczenia na które zostanie podana odpowiedź, minimum 5 znaków."
      answer:
        type: "string"
        description: "Odpowiedź na zadane pytanie, która zostanie nauczona, minimum 5 znaków."
    xml:
      name: "QuestionLearnData"