swagger: '2.0'
schemes:
  - http
basePath: /
info:
  version: 1.0.0
  title: ChatBot API
  description: Projekt zaliczeniowy na zajęcia z Projektu Programistycznego, Uniwersytet Ekonomiczny w Katowicach, informatyka, niestacjonarne, 2 grupa, rok 2021/2022
tags:
  - name: main
    description: komendy ogólne związane z API
  - name: spambot
    description: komendy związane z obsługą ChatBota rozpoznającego tekst będący spamem

paths:
  /:
    get:
      summary: informacje o API i jego autorach
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            example: {
              'przedmiot': 'Projekt programistyczny',
              'kierunek': 'Informatyka',
              'grupa': 'Studia niestacjonarne',
              'rok': '2021/2022',
              'uczelnia': 'Uniwersytet Ekonomiczny',
              'autorzy': [
                'Artur Leśnik',
                'Alicja Pęgiel'
              ]
            }
      tags:
        - main